/*
 * Initial main.c file generated by Glade. Edit as required. Glade will not
 * overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

#include "defs.h"
#include "face.h"

int
face_uses_X ()
{
    return TRUE;
}

int
face_run (int argc, char *argv[])
{
    GtkWidget *gems;

#ifdef ENABLE_NLS
    bindtextdomain (PACKAGE, PACKAGE_LOCALE_DIR);
    textdomain (PACKAGE);
#endif

    gtk_set_locale ();
    gtk_init (&argc, &argv);

    /*
     * The following code was added by Glade to create one of each component
     * (except popup menus), just so that you see something after building
     * the project. Delete any components that you don't want shown
     * initially.
     */
    gems = create_gems ();
    gtk_widget_show (gems);

    gtk_main ();
    return 0;
}
