/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <bonobo.h>
#include <gnome.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

static GnomeUIInfo file1_menu_uiinfo[] =
{
  GNOMEUIINFO_MENU_NEW_ITEM (N_("_New"), NULL, on_new1_activate, NULL),
  GNOMEUIINFO_MENU_OPEN_ITEM (on_open1_activate, NULL),
  GNOMEUIINFO_MENU_SAVE_ITEM (on_save1_activate, NULL),
  GNOMEUIINFO_MENU_SAVE_AS_ITEM (on_save_as1_activate, NULL),
  GNOMEUIINFO_SEPARATOR,
  GNOMEUIINFO_MENU_EXIT_ITEM (on_quit1_activate, NULL),
  GNOMEUIINFO_END
};

static GnomeUIInfo edit1_menu_uiinfo[] =
{
  GNOMEUIINFO_MENU_CUT_ITEM (on_cut1_activate, NULL),
  GNOMEUIINFO_MENU_COPY_ITEM (on_copy1_activate, NULL),
  GNOMEUIINFO_MENU_PASTE_ITEM (on_paste1_activate, NULL),
  GNOMEUIINFO_MENU_CLEAR_ITEM (on_clear1_activate, NULL),
  GNOMEUIINFO_SEPARATOR,
  GNOMEUIINFO_MENU_PROPERTIES_ITEM (on_properties1_activate, NULL),
  GNOMEUIINFO_SEPARATOR,
  GNOMEUIINFO_MENU_PREFERENCES_ITEM (on_preferences1_activate, NULL),
  GNOMEUIINFO_END
};

static GnomeUIInfo view1_uiinfo[] =
{
  GNOMEUIINFO_END
};

static GnomeUIInfo help1_menu_uiinfo[] =
{
  GNOMEUIINFO_HELP ("gems"),
  GNOMEUIINFO_MENU_ABOUT_ITEM (on_about1_activate, NULL),
  GNOMEUIINFO_END
};

static GnomeUIInfo menubar_uiinfo[] =
{
  GNOMEUIINFO_MENU_FILE_TREE (file1_menu_uiinfo),
  GNOMEUIINFO_MENU_EDIT_TREE (edit1_menu_uiinfo),
  GNOMEUIINFO_MENU_VIEW_TREE (view1_uiinfo),
  GNOMEUIINFO_MENU_HELP_TREE (help1_menu_uiinfo),
  GNOMEUIINFO_END
};

GtkWidget*
create_gems (void)
{
  GtkWidget *gems;
  GtkWidget *bonobodock1;
  GtkWidget *toolbar1;
  GtkIconSize tmp_toolbar_icon_size;
  GtkWidget *tmp_image;
  GtkWidget *toolbar_compose;
  GtkWidget *toolbar_reply;
  GtkWidget *toolbar_forward;
  GtkWidget *separatortoolitem1;
  GtkWidget *toolbar_prev;
  GtkWidget *toolbar_next;
  GtkWidget *separatortoolitem2;
  GtkWidget *toolbar_rules;
  GtkWidget *hpaned1;
  GtkWidget *scrolledwindow1;
  GtkWidget *mboxlist;
  GtkWidget *vpaned1;
  GtkWidget *scrolledwindow2;
  GtkWidget *mbox;
  GtkWidget *vbox1;
  GtkWidget *table1;
  GtkWidget *msg_from;
  GtkWidget *msg_date;
  GtkWidget *msg_subject;
  GtkWidget *msg_recipt;
  GtkWidget *label1;
  GtkWidget *label2;
  GtkWidget *label3;
  GtkWidget *label4;
  GtkWidget *scrolledwindow3;
  GtkWidget *msg_body;
  GtkWidget *appbar1;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  gems = gnome_app_new ("gems", _("GEMS"));

  bonobodock1 = GNOME_APP (gems)->dock;
  gtk_widget_show (bonobodock1);

  gnome_app_create_menus (GNOME_APP (gems), menubar_uiinfo);

  toolbar1 = gtk_toolbar_new ();
  gtk_widget_show (toolbar1);
  gnome_app_add_toolbar (GNOME_APP (gems), GTK_TOOLBAR (toolbar1), "toolbar1",
                                BONOBO_DOCK_ITEM_BEH_EXCLUSIVE,
                                BONOBO_DOCK_TOP, 1, 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (toolbar1), 1);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar1), GTK_TOOLBAR_ICONS);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1));

  tmp_image = gtk_image_new_from_stock ("gnome-stock-mail-new", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  toolbar_compose = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Compose"));
  gtk_widget_show (toolbar_compose);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbar_compose);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (toolbar_compose), tooltips, _("Compose new message"), NULL);

  tmp_image = gtk_image_new_from_stock ("gnome-stock-mail-rpl", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  toolbar_reply = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Reply"));
  gtk_widget_show (toolbar_reply);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbar_reply);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (toolbar_reply), tooltips, _("Reply"), NULL);

  tmp_image = gtk_image_new_from_stock ("gnome-stock-mail-fwd", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  toolbar_forward = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Forward"));
  gtk_widget_show (toolbar_forward);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbar_forward);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (toolbar_forward), tooltips, _("Forward"), NULL);

  separatortoolitem1 = (GtkWidget*) gtk_separator_tool_item_new ();
  gtk_widget_show (separatortoolitem1);
  gtk_container_add (GTK_CONTAINER (toolbar1), separatortoolitem1);

  tmp_image = gtk_image_new_from_stock ("gtk-go-back", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  toolbar_prev = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Previous"));
  gtk_widget_show (toolbar_prev);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbar_prev);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (toolbar_prev), tooltips, _("Previous"), NULL);

  tmp_image = gtk_image_new_from_stock ("gtk-go-forward", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  toolbar_next = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Next"));
  gtk_widget_show (toolbar_next);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbar_next);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (toolbar_next), tooltips, _("Next"), NULL);

  separatortoolitem2 = (GtkWidget*) gtk_separator_tool_item_new ();
  gtk_widget_show (separatortoolitem2);
  gtk_container_add (GTK_CONTAINER (toolbar1), separatortoolitem2);

  tmp_image = gtk_image_new_from_stock ("gnome-stock-book-red", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  toolbar_rules = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Rules"));
  gtk_widget_show (toolbar_rules);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbar_rules);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (toolbar_rules), tooltips, _("Rules"), NULL);

  hpaned1 = gtk_hpaned_new ();
  gtk_widget_show (hpaned1);
  gnome_app_set_contents (GNOME_APP (gems), hpaned1);
  gtk_paned_set_position (GTK_PANED (hpaned1), 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_paned_pack1 (GTK_PANED (hpaned1), scrolledwindow1, FALSE, TRUE);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  mboxlist = gtk_tree_view_new ();
  gtk_widget_show (mboxlist);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), mboxlist);
  gtk_tree_view_set_headers_visible (GTK_TREE_VIEW (mboxlist), FALSE);

  vpaned1 = gtk_vpaned_new ();
  gtk_widget_show (vpaned1);
  gtk_paned_pack2 (GTK_PANED (hpaned1), vpaned1, TRUE, TRUE);
  gtk_paned_set_position (GTK_PANED (vpaned1), 0);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_paned_pack1 (GTK_PANED (vpaned1), scrolledwindow2, FALSE, TRUE);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  mbox = gtk_tree_view_new ();
  gtk_widget_show (mbox);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), mbox);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_paned_pack2 (GTK_PANED (vpaned1), vbox1, TRUE, TRUE);

  table1 = gtk_table_new (4, 2, FALSE);
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (vbox1), table1, FALSE, FALSE, 0);

  msg_from = gtk_entry_new ();
  gtk_widget_show (msg_from);
  gtk_table_attach (GTK_TABLE (table1), msg_from, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_editable_set_editable (GTK_EDITABLE (msg_from), FALSE);

  msg_date = gtk_entry_new ();
  gtk_widget_show (msg_date);
  gtk_table_attach (GTK_TABLE (table1), msg_date, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_editable_set_editable (GTK_EDITABLE (msg_date), FALSE);

  msg_subject = gtk_entry_new ();
  gtk_widget_show (msg_subject);
  gtk_table_attach (GTK_TABLE (table1), msg_subject, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_editable_set_editable (GTK_EDITABLE (msg_subject), FALSE);

  msg_recipt = gtk_entry_new ();
  gtk_widget_show (msg_recipt);
  gtk_table_attach (GTK_TABLE (table1), msg_recipt, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_editable_set_editable (GTK_EDITABLE (msg_recipt), FALSE);

  label1 = gtk_label_new (_("From"));
  gtk_widget_show (label1);
  gtk_table_attach (GTK_TABLE (table1), label1, 0, 1, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label1), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (label1), 0, 0.5);

  label2 = gtk_label_new (_("Date"));
  gtk_widget_show (label2);
  gtk_table_attach (GTK_TABLE (table1), label2, 0, 1, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label2), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (label2), 0, 0.5);

  label3 = gtk_label_new (_("Subject"));
  gtk_widget_show (label3);
  gtk_table_attach (GTK_TABLE (table1), label3, 0, 1, 2, 3,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label3), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (label3), 0, 0.5);

  label4 = gtk_label_new (_("Recipients"));
  gtk_widget_show (label4);
  gtk_table_attach (GTK_TABLE (table1), label4, 0, 1, 3, 4,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label4), 0, 0.5);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_box_pack_start (GTK_BOX (vbox1), scrolledwindow3, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  msg_body = gtk_text_view_new ();
  gtk_widget_show (msg_body);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), msg_body);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (msg_body), FALSE);

  appbar1 = gnome_appbar_new (TRUE, TRUE, GNOME_PREFERENCES_NEVER);
  gtk_widget_show (appbar1);
  gnome_app_set_statusbar (GNOME_APP (gems), appbar1);

  g_signal_connect ((gpointer) gems, "delete_event",
                    G_CALLBACK (on_gems_delete_event),
                    NULL);
  g_signal_connect ((gpointer) gems, "destroy_event",
                    G_CALLBACK (on_gems_destroy_event),
                    NULL);
  gnome_app_install_menu_hints (GNOME_APP (gems), menubar_uiinfo);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gems, gems, "gems");
  GLADE_HOOKUP_OBJECT (gems, bonobodock1, "bonobodock1");
  GLADE_HOOKUP_OBJECT (gems, menubar_uiinfo[0].widget, "file1");
  GLADE_HOOKUP_OBJECT (gems, file1_menu_uiinfo[0].widget, "new1");
  GLADE_HOOKUP_OBJECT (gems, file1_menu_uiinfo[1].widget, "open1");
  GLADE_HOOKUP_OBJECT (gems, file1_menu_uiinfo[2].widget, "save1");
  GLADE_HOOKUP_OBJECT (gems, file1_menu_uiinfo[3].widget, "save_as1");
  GLADE_HOOKUP_OBJECT (gems, file1_menu_uiinfo[4].widget, "separator1");
  GLADE_HOOKUP_OBJECT (gems, file1_menu_uiinfo[5].widget, "quit1");
  GLADE_HOOKUP_OBJECT (gems, menubar_uiinfo[1].widget, "edit1");
  GLADE_HOOKUP_OBJECT (gems, edit1_menu_uiinfo[0].widget, "cut1");
  GLADE_HOOKUP_OBJECT (gems, edit1_menu_uiinfo[1].widget, "copy1");
  GLADE_HOOKUP_OBJECT (gems, edit1_menu_uiinfo[2].widget, "paste1");
  GLADE_HOOKUP_OBJECT (gems, edit1_menu_uiinfo[3].widget, "clear1");
  GLADE_HOOKUP_OBJECT (gems, edit1_menu_uiinfo[4].widget, "separator2");
  GLADE_HOOKUP_OBJECT (gems, edit1_menu_uiinfo[5].widget, "properties1");
  GLADE_HOOKUP_OBJECT (gems, edit1_menu_uiinfo[6].widget, "separator3");
  GLADE_HOOKUP_OBJECT (gems, edit1_menu_uiinfo[7].widget, "preferences1");
  GLADE_HOOKUP_OBJECT (gems, menubar_uiinfo[2].widget, "view1");
  GLADE_HOOKUP_OBJECT (gems, menubar_uiinfo[3].widget, "help1");
  GLADE_HOOKUP_OBJECT (gems, help1_menu_uiinfo[1].widget, "about1");
  GLADE_HOOKUP_OBJECT (gems, toolbar1, "toolbar1");
  GLADE_HOOKUP_OBJECT (gems, toolbar_compose, "toolbar_compose");
  GLADE_HOOKUP_OBJECT (gems, toolbar_reply, "toolbar_reply");
  GLADE_HOOKUP_OBJECT (gems, toolbar_forward, "toolbar_forward");
  GLADE_HOOKUP_OBJECT (gems, separatortoolitem1, "separatortoolitem1");
  GLADE_HOOKUP_OBJECT (gems, toolbar_prev, "toolbar_prev");
  GLADE_HOOKUP_OBJECT (gems, toolbar_next, "toolbar_next");
  GLADE_HOOKUP_OBJECT (gems, separatortoolitem2, "separatortoolitem2");
  GLADE_HOOKUP_OBJECT (gems, toolbar_rules, "toolbar_rules");
  GLADE_HOOKUP_OBJECT (gems, hpaned1, "hpaned1");
  GLADE_HOOKUP_OBJECT (gems, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (gems, mboxlist, "mboxlist");
  GLADE_HOOKUP_OBJECT (gems, vpaned1, "vpaned1");
  GLADE_HOOKUP_OBJECT (gems, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (gems, mbox, "mbox");
  GLADE_HOOKUP_OBJECT (gems, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (gems, table1, "table1");
  GLADE_HOOKUP_OBJECT (gems, msg_from, "msg_from");
  GLADE_HOOKUP_OBJECT (gems, msg_date, "msg_date");
  GLADE_HOOKUP_OBJECT (gems, msg_subject, "msg_subject");
  GLADE_HOOKUP_OBJECT (gems, msg_recipt, "msg_recipt");
  GLADE_HOOKUP_OBJECT (gems, label1, "label1");
  GLADE_HOOKUP_OBJECT (gems, label2, "label2");
  GLADE_HOOKUP_OBJECT (gems, label3, "label3");
  GLADE_HOOKUP_OBJECT (gems, label4, "label4");
  GLADE_HOOKUP_OBJECT (gems, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (gems, msg_body, "msg_body");
  GLADE_HOOKUP_OBJECT (gems, appbar1, "appbar1");
  GLADE_HOOKUP_OBJECT_NO_REF (gems, tooltips, "tooltips");

  return gems;
}

GtkWidget*
create_about (void)
{
  const gchar *authors[] = {
    "Erik Greenwald",
    NULL
  };
  const gchar *documenters[] = { NULL };
  /* TRANSLATORS: Replace this string with your names, one name per line. */
  gchar *translators = _("translator_credits");
  GtkWidget *about;

  if (!strcmp (translators, "translator_credits"))
    translators = NULL;
  about = gnome_about_new ("gems", VERSION,
                        _("(C) 2000-2005 Erik Greenwald"),
                        _("GEMS E-Mail System"),
                        authors,
                        documenters,
                        translators,
                        NULL);
  gtk_container_set_border_width (GTK_CONTAINER (about), 5);
  gtk_window_set_type_hint (GTK_WINDOW (about), GDK_WINDOW_TYPE_HINT_DIALOG);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (about, about, "about");

  return about;
}

