/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

/*
 * $Id: main.c,v 1.9 2010/05/28 00:20:05 erik Exp $
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gnome.h>

int
face_uses_X ()
{
    return TRUE;
}

int
face_run (int argc, char *argv[])
{
    GtkWidget *top, *mboxlist;
    GtkCellRenderer *renderer;

#ifdef ENABLE_NLS
    bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
    bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
    textdomain (GETTEXT_PACKAGE);
#endif

    gnome_program_init (PACKAGE, VERSION, LIBGNOMEUI_MODULE,
	    argc, argv,
	    GNOME_PARAM_APP_DATADIR, PACKAGE_DATA_DIR,
	    NULL);

    top = create_gems();
    mboxlist = lookup_widget(top, "mboxlist");

    renderer = gtk_cell_renderer_text_new ();
    gtk_tree_view_insert_column_with_attributes (GTK_TREE_VIEW (mboxlist), -1, "Name", renderer, "text", 0, NULL);
    renderer = gtk_cell_renderer_text_new ();
    gtk_tree_view_insert_column_with_attributes (GTK_TREE_VIEW (mboxlist), -1, "Unread", renderer, "text", 1, NULL);

    gtk_widget_show(top);

    set_mboxlist(top);
    gtk_main ();
    return 0;
}

