/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gnome.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

static GnomeUIInfo file1_menu_uiinfo[] =
{
  GNOMEUIINFO_MENU_NEW_ITEM (N_("_New File"), NULL, on_new_file1_activate, NULL),
  GNOMEUIINFO_MENU_OPEN_ITEM (on_open1_activate, NULL),
  GNOMEUIINFO_MENU_SAVE_ITEM (on_save1_activate, NULL),
  GNOMEUIINFO_MENU_SAVE_AS_ITEM (on_save_as1_activate, NULL),
  GNOMEUIINFO_SEPARATOR,
  GNOMEUIINFO_MENU_EXIT_ITEM (on_gems_quit, NULL),
  GNOMEUIINFO_END
};

static GnomeUIInfo edit1_menu_uiinfo[] =
{
  GNOMEUIINFO_MENU_CUT_ITEM (on_cut1_activate, NULL),
  GNOMEUIINFO_MENU_COPY_ITEM (on_copy1_activate, NULL),
  GNOMEUIINFO_MENU_PASTE_ITEM (on_paste1_activate, NULL),
  GNOMEUIINFO_MENU_CLEAR_ITEM (on_clear1_activate, NULL),
  GNOMEUIINFO_SEPARATOR,
  GNOMEUIINFO_MENU_PROPERTIES_ITEM (on_properties1_activate, NULL),
  GNOMEUIINFO_END
};

static GnomeUIInfo view1_menu_uiinfo[] =
{
  GNOMEUIINFO_END
};

static GnomeUIInfo settings1_menu_uiinfo[] =
{
  GNOMEUIINFO_MENU_PREFERENCES_ITEM (on_preferences1_activate, NULL),
  GNOMEUIINFO_END
};

static GnomeUIInfo help1_menu_uiinfo[] =
{
  GNOMEUIINFO_MENU_ABOUT_ITEM (on_about1_activate, NULL),
  GNOMEUIINFO_END
};

static GnomeUIInfo menubar1_uiinfo[] =
{
  GNOMEUIINFO_MENU_FILE_TREE (file1_menu_uiinfo),
  GNOMEUIINFO_MENU_EDIT_TREE (edit1_menu_uiinfo),
  GNOMEUIINFO_MENU_VIEW_TREE (view1_menu_uiinfo),
  GNOMEUIINFO_MENU_SETTINGS_TREE (settings1_menu_uiinfo),
  {
    GNOME_APP_UI_SUBTREE, N_("_Help"),
    NULL,
    help1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

GtkWidget*
create_gems (void)
{
  GtkWidget *gems;
  GtkWidget *dock1;
  GtkWidget *toolbar1;
  GtkWidget *tmp_toolbar_icon;
  GtkWidget *toolbar_compose;
  GtkWidget *toolbar_reply;
  GtkWidget *toolbar_forward;
  GtkWidget *toolbar_prev;
  GtkWidget *toolbar_next;
  GtkWidget *toolbar_rule;
  GtkWidget *hpaned1;
  GtkWidget *scrolledwindow5;
  GtkWidget *ctree2;
  GtkWidget *label8;
  GtkWidget *vpaned1;
  GtkWidget *scrolledwindow1;
  GtkWidget *ctree1;
  GtkWidget *label1;
  GtkWidget *label2;
  GtkWidget *label3;
  GtkWidget *vbox1;
  GtkWidget *table1;
  GtkWidget *label4;
  GtkWidget *label5;
  GtkWidget *label6;
  GtkWidget *label7;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *entry3;
  GtkWidget *entry4;
  GtkWidget *scrolledwindow3;
  GtkWidget *text1;
  GtkWidget *appbar1;

  gems = gnome_app_new ("gems", _("gems"));
  gtk_object_set_data (GTK_OBJECT (gems), "gems", gems);

  dock1 = GNOME_APP (gems)->dock;
  gtk_widget_ref (dock1);
  gtk_object_set_data_full (GTK_OBJECT (gems), "dock1", dock1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (dock1);

  gnome_app_create_menus (GNOME_APP (gems), menubar1_uiinfo);

  gtk_widget_ref (menubar1_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (gems), "file1",
                            menubar1_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (file1_menu_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (gems), "new_file1",
                            file1_menu_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (file1_menu_uiinfo[1].widget);
  gtk_object_set_data_full (GTK_OBJECT (gems), "open1",
                            file1_menu_uiinfo[1].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (file1_menu_uiinfo[2].widget);
  gtk_object_set_data_full (GTK_OBJECT (gems), "save1",
                            file1_menu_uiinfo[2].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (file1_menu_uiinfo[3].widget);
  gtk_object_set_data_full (GTK_OBJECT (gems), "save_as1",
                            file1_menu_uiinfo[3].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (file1_menu_uiinfo[4].widget);
  gtk_object_set_data_full (GTK_OBJECT (gems), "separator1",
                            file1_menu_uiinfo[4].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (file1_menu_uiinfo[5].widget);
  gtk_object_set_data_full (GTK_OBJECT (gems), "exit1",
                            file1_menu_uiinfo[5].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (menubar1_uiinfo[1].widget);
  gtk_object_set_data_full (GTK_OBJECT (gems), "edit1",
                            menubar1_uiinfo[1].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (edit1_menu_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (gems), "cut1",
                            edit1_menu_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (edit1_menu_uiinfo[1].widget);
  gtk_object_set_data_full (GTK_OBJECT (gems), "copy1",
                            edit1_menu_uiinfo[1].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (edit1_menu_uiinfo[2].widget);
  gtk_object_set_data_full (GTK_OBJECT (gems), "paste1",
                            edit1_menu_uiinfo[2].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (edit1_menu_uiinfo[3].widget);
  gtk_object_set_data_full (GTK_OBJECT (gems), "clear1",
                            edit1_menu_uiinfo[3].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (edit1_menu_uiinfo[4].widget);
  gtk_object_set_data_full (GTK_OBJECT (gems), "separator2",
                            edit1_menu_uiinfo[4].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (edit1_menu_uiinfo[5].widget);
  gtk_object_set_data_full (GTK_OBJECT (gems), "properties1",
                            edit1_menu_uiinfo[5].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (menubar1_uiinfo[2].widget);
  gtk_object_set_data_full (GTK_OBJECT (gems), "view1",
                            menubar1_uiinfo[2].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (menubar1_uiinfo[3].widget);
  gtk_object_set_data_full (GTK_OBJECT (gems), "settings1",
                            menubar1_uiinfo[3].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (settings1_menu_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (gems), "preferences1",
                            settings1_menu_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (menubar1_uiinfo[4].widget);
  gtk_object_set_data_full (GTK_OBJECT (gems), "help1",
                            menubar1_uiinfo[4].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (help1_menu_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (gems), "about1",
                            help1_menu_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  toolbar1 = gtk_toolbar_new (GTK_ORIENTATION_HORIZONTAL, GTK_TOOLBAR_ICONS);
  gtk_widget_ref (toolbar1);
  gtk_object_set_data_full (GTK_OBJECT (gems), "toolbar1", toolbar1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toolbar1);
  gnome_app_add_toolbar (GNOME_APP (gems), GTK_TOOLBAR (toolbar1), "toolbar1",
                                GNOME_DOCK_ITEM_BEH_EXCLUSIVE,
                                GNOME_DOCK_TOP, 1, 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (toolbar1), 1);
  gtk_toolbar_set_space_size (GTK_TOOLBAR (toolbar1), 16);
  gtk_toolbar_set_space_style (GTK_TOOLBAR (toolbar1), GTK_TOOLBAR_SPACE_LINE);

  tmp_toolbar_icon = gnome_stock_pixmap_widget (gems, GNOME_STOCK_PIXMAP_MAIL_NEW);
  toolbar_compose = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Compose"),
                                _("Compose"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (toolbar_compose);
  gtk_object_set_data_full (GTK_OBJECT (gems), "toolbar_compose", toolbar_compose,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toolbar_compose);

  tmp_toolbar_icon = gnome_stock_pixmap_widget (gems, GNOME_STOCK_PIXMAP_MAIL_RPL);
  toolbar_reply = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Reply"),
                                _("Reply"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (toolbar_reply);
  gtk_object_set_data_full (GTK_OBJECT (gems), "toolbar_reply", toolbar_reply,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toolbar_reply);

  tmp_toolbar_icon = gnome_stock_pixmap_widget (gems, GNOME_STOCK_PIXMAP_MAIL_FWD);
  toolbar_forward = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Forward"),
                                _("Forward"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (toolbar_forward);
  gtk_object_set_data_full (GTK_OBJECT (gems), "toolbar_forward", toolbar_forward,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toolbar_forward);

  gtk_toolbar_append_space (GTK_TOOLBAR (toolbar1));

  tmp_toolbar_icon = gnome_stock_pixmap_widget (gems, GNOME_STOCK_PIXMAP_BACK);
  toolbar_prev = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Previous"),
                                _("Previous"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (toolbar_prev);
  gtk_object_set_data_full (GTK_OBJECT (gems), "toolbar_prev", toolbar_prev,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toolbar_prev);

  tmp_toolbar_icon = gnome_stock_pixmap_widget (gems, GNOME_STOCK_PIXMAP_FORWARD);
  toolbar_next = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Next"),
                                _("Next"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (toolbar_next);
  gtk_object_set_data_full (GTK_OBJECT (gems), "toolbar_next", toolbar_next,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toolbar_next);

  gtk_toolbar_append_space (GTK_TOOLBAR (toolbar1));

  tmp_toolbar_icon = gnome_stock_pixmap_widget (gems, GNOME_STOCK_PIXMAP_BOOK_RED);
  toolbar_rule = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Rules"),
                                _("Rules"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (toolbar_rule);
  gtk_object_set_data_full (GTK_OBJECT (gems), "toolbar_rule", toolbar_rule,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toolbar_rule);

  hpaned1 = gtk_hpaned_new ();
  gtk_widget_ref (hpaned1);
  gtk_object_set_data_full (GTK_OBJECT (gems), "hpaned1", hpaned1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hpaned1);
  gnome_app_set_contents (GNOME_APP (gems), hpaned1);
  gtk_paned_set_position (GTK_PANED (hpaned1), 0);

  scrolledwindow5 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow5);
  gtk_object_set_data_full (GTK_OBJECT (gems), "scrolledwindow5", scrolledwindow5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow5);
  gtk_paned_pack1 (GTK_PANED (hpaned1), scrolledwindow5, FALSE, FALSE);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow5), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  ctree2 = gtk_ctree_new (1, 0);
  gtk_widget_ref (ctree2);
  gtk_object_set_data_full (GTK_OBJECT (gems), "ctree2", ctree2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (ctree2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow5), ctree2);
  gtk_clist_set_column_width (GTK_CLIST (ctree2), 0, 80);
  gtk_clist_column_titles_hide (GTK_CLIST (ctree2));

  label8 = gtk_label_new ("");
  gtk_widget_ref (label8);
  gtk_object_set_data_full (GTK_OBJECT (gems), "label8", label8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label8);
  gtk_clist_set_column_widget (GTK_CLIST (ctree2), 0, label8);

  vpaned1 = gtk_vpaned_new ();
  gtk_widget_ref (vpaned1);
  gtk_object_set_data_full (GTK_OBJECT (gems), "vpaned1", vpaned1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vpaned1);
  gtk_paned_pack2 (GTK_PANED (hpaned1), vpaned1, TRUE, TRUE);
  gtk_paned_set_position (GTK_PANED (vpaned1), 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow1);
  gtk_object_set_data_full (GTK_OBJECT (gems), "scrolledwindow1", scrolledwindow1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow1);
  gtk_paned_pack1 (GTK_PANED (vpaned1), scrolledwindow1, FALSE, FALSE);
  gtk_widget_set_usize (scrolledwindow1, -2, 70);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  ctree1 = gtk_ctree_new (3, 0);
  gtk_widget_ref (ctree1);
  gtk_object_set_data_full (GTK_OBJECT (gems), "ctree1", ctree1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (ctree1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), ctree1);
  gtk_clist_set_column_width (GTK_CLIST (ctree1), 0, 80);
  gtk_clist_set_column_width (GTK_CLIST (ctree1), 1, 80);
  gtk_clist_set_column_width (GTK_CLIST (ctree1), 2, 80);
  gtk_clist_set_selection_mode (GTK_CLIST (ctree1), GTK_SELECTION_EXTENDED);
  gtk_clist_column_titles_show (GTK_CLIST (ctree1));

  label1 = gtk_label_new (_("Sender"));
  gtk_widget_ref (label1);
  gtk_object_set_data_full (GTK_OBJECT (gems), "label1", label1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label1);
  gtk_clist_set_column_widget (GTK_CLIST (ctree1), 0, label1);

  label2 = gtk_label_new (_("Date"));
  gtk_widget_ref (label2);
  gtk_object_set_data_full (GTK_OBJECT (gems), "label2", label2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label2);
  gtk_clist_set_column_widget (GTK_CLIST (ctree1), 1, label2);

  label3 = gtk_label_new (_("Subject"));
  gtk_widget_ref (label3);
  gtk_object_set_data_full (GTK_OBJECT (gems), "label3", label3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label3);
  gtk_clist_set_column_widget (GTK_CLIST (ctree1), 2, label3);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (gems), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_paned_pack2 (GTK_PANED (vpaned1), vbox1, TRUE, TRUE);

  table1 = gtk_table_new (4, 2, FALSE);
  gtk_widget_ref (table1);
  gtk_object_set_data_full (GTK_OBJECT (gems), "table1", table1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (vbox1), table1, FALSE, FALSE, 0);

  label4 = gtk_label_new (_("From"));
  gtk_widget_ref (label4);
  gtk_object_set_data_full (GTK_OBJECT (gems), "label4", label4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label4);
  gtk_table_attach (GTK_TABLE (table1), label4, 0, 1, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label5 = gtk_label_new (_("Date"));
  gtk_widget_ref (label5);
  gtk_object_set_data_full (GTK_OBJECT (gems), "label5", label5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label5);
  gtk_table_attach (GTK_TABLE (table1), label5, 0, 1, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label6 = gtk_label_new (_("Subject"));
  gtk_widget_ref (label6);
  gtk_object_set_data_full (GTK_OBJECT (gems), "label6", label6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label6);
  gtk_table_attach (GTK_TABLE (table1), label6, 0, 1, 2, 3,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label7 = gtk_label_new (_("Recipients"));
  gtk_widget_ref (label7);
  gtk_object_set_data_full (GTK_OBJECT (gems), "label7", label7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label7);
  gtk_table_attach (GTK_TABLE (table1), label7, 0, 1, 3, 4,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  entry1 = gtk_entry_new ();
  gtk_widget_ref (entry1);
  gtk_object_set_data_full (GTK_OBJECT (gems), "entry1", entry1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry1);
  gtk_table_attach (GTK_TABLE (table1), entry1, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (entry1, GTK_CAN_FOCUS);
  gtk_entry_set_editable (GTK_ENTRY (entry1), FALSE);

  entry2 = gtk_entry_new ();
  gtk_widget_ref (entry2);
  gtk_object_set_data_full (GTK_OBJECT (gems), "entry2", entry2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry2);
  gtk_table_attach (GTK_TABLE (table1), entry2, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (entry2, GTK_CAN_FOCUS);
  gtk_entry_set_editable (GTK_ENTRY (entry2), FALSE);

  entry3 = gtk_entry_new ();
  gtk_widget_ref (entry3);
  gtk_object_set_data_full (GTK_OBJECT (gems), "entry3", entry3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry3);
  gtk_table_attach (GTK_TABLE (table1), entry3, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (entry3, GTK_CAN_FOCUS);
  gtk_entry_set_editable (GTK_ENTRY (entry3), FALSE);

  entry4 = gtk_entry_new ();
  gtk_widget_ref (entry4);
  gtk_object_set_data_full (GTK_OBJECT (gems), "entry4", entry4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry4);
  gtk_table_attach (GTK_TABLE (table1), entry4, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (entry4, GTK_CAN_FOCUS);
  gtk_entry_set_editable (GTK_ENTRY (entry4), FALSE);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow3);
  gtk_object_set_data_full (GTK_OBJECT (gems), "scrolledwindow3", scrolledwindow3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow3);
  gtk_box_pack_start (GTK_BOX (vbox1), scrolledwindow3, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  text1 = gtk_text_new (NULL, NULL);
  gtk_widget_ref (text1);
  gtk_object_set_data_full (GTK_OBJECT (gems), "text1", text1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (text1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), text1);

  appbar1 = gnome_appbar_new (TRUE, TRUE, GNOME_PREFERENCES_NEVER);
  gtk_widget_ref (appbar1);
  gtk_object_set_data_full (GTK_OBJECT (gems), "appbar1", appbar1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (appbar1);
  gnome_app_set_statusbar (GNOME_APP (gems), appbar1);

  gtk_signal_connect (GTK_OBJECT (gems), "destroy_event",
                      GTK_SIGNAL_FUNC (on_gems_quit),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (gems), "delete_event",
                      GTK_SIGNAL_FUNC (on_gems_quit),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (gems), "destroy",
                      GTK_SIGNAL_FUNC (on_gems_quit),
                      NULL);
  gnome_app_install_menu_hints (GNOME_APP (gems), menubar1_uiinfo);
  gtk_signal_connect (GTK_OBJECT (toolbar_compose), "clicked",
                      GTK_SIGNAL_FUNC (on_toolbar_compose_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (toolbar_reply), "clicked",
                      GTK_SIGNAL_FUNC (on_toolbar_reply_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (toolbar_forward), "clicked",
                      GTK_SIGNAL_FUNC (on_toolbar_forward_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (toolbar_prev), "clicked",
                      GTK_SIGNAL_FUNC (on_toolbar_prev_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (toolbar_next), "clicked",
                      GTK_SIGNAL_FUNC (on_toolbar_next_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (toolbar_rule), "clicked",
                      GTK_SIGNAL_FUNC (on_toolbar_rule_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (ctree2), "tree_select_row",
                      GTK_SIGNAL_FUNC (on_ctree2_tree_select_row),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (ctree2), "event",
                      GTK_SIGNAL_FUNC (on_mboxlist_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (ctree2), "key_press_event",
                      GTK_SIGNAL_FUNC (on_mboxlist_keyevent),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (ctree1), "event",
                      GTK_SIGNAL_FUNC (on_ctree1_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (ctree1), "key_press_event",
                      GTK_SIGNAL_FUNC (on_ctree1_key_press_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (ctree1), "click_column",
                      GTK_SIGNAL_FUNC (on_ctree1_click_column),
                      NULL);

  return gems;
}

GtkWidget*
create_about2 (void)
{
  const gchar *authors[] = {
    "Erik Greenwald <erik@smluc.org>",
    NULL
  };
  GtkWidget *about2;

  about2 = gnome_about_new ("gems", VERSION,
                        _("Copyright (C) 2000 Erik Greenwald"),
                        authors,
                        "",
                        NULL);
  gtk_object_set_data (GTK_OBJECT (about2), "about2", about2);
  gtk_window_set_modal (GTK_WINDOW (about2), TRUE);

  return about2;
}

static GnomeUIInfo menu1_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("Create"),
    NULL,
    (gpointer) on_create1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("Open"),
    NULL,
    (gpointer) on_open2_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("Custom"),
    NULL,
    (gpointer) on_custom1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("Delete"),
    NULL,
    (gpointer) on_delete1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

GtkWidget*
create_menu1 (void)
{
  GtkWidget *menu1;

  menu1 = gtk_menu_new ();
  gtk_object_set_data (GTK_OBJECT (menu1), "menu1", menu1);
  gnome_app_fill_menu (GTK_MENU_SHELL (menu1), menu1_uiinfo,
                       NULL, FALSE, 0);

  gtk_widget_ref (menu1_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (menu1), "create1",
                            menu1_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (menu1_uiinfo[1].widget);
  gtk_object_set_data_full (GTK_OBJECT (menu1), "open2",
                            menu1_uiinfo[1].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (menu1_uiinfo[2].widget);
  gtk_object_set_data_full (GTK_OBJECT (menu1), "custom1",
                            menu1_uiinfo[2].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (menu1_uiinfo[3].widget);
  gtk_object_set_data_full (GTK_OBJECT (menu1), "delete1",
                            menu1_uiinfo[3].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  return menu1;
}

GtkWidget*
create_compose (void)
{
  GtkWidget *compose;
  GtkWidget *vbox2;
  GtkWidget *handlebox1;
  GtkWidget *toolbar2;
  GtkWidget *tmp_toolbar_icon;
  GtkWidget *button6;
  GtkWidget *button7;
  GtkWidget *button8;
  GtkWidget *table2;
  GtkWidget *optionmenu1;
  GtkWidget *optionmenu1_menu;
  GtkWidget *glade_menuitem;
  GtkWidget *label9;
  GtkWidget *label10;
  GtkWidget *label11;
  GtkWidget *entry6;
  GtkWidget *label12;
  GtkWidget *hbox2;
  GtkWidget *combo1;
  GtkWidget *combo_entry1;
  GtkWidget *button5;
  GtkWidget *hbox1;
  GtkWidget *entry5;
  GtkWidget *button3;
  GtkWidget *button4;
  GtkWidget *scrolledwindow6;
  GtkWidget *text2;
  GtkWidget *statusbar1;

  compose = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (compose), "compose", compose);
  gtk_window_set_title (GTK_WINDOW (compose), _("Compose Message"));

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox2);
  gtk_object_set_data_full (GTK_OBJECT (compose), "vbox2", vbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (compose), vbox2);

  handlebox1 = gtk_handle_box_new ();
  gtk_widget_ref (handlebox1);
  gtk_object_set_data_full (GTK_OBJECT (compose), "handlebox1", handlebox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (handlebox1);
  gtk_box_pack_start (GTK_BOX (vbox2), handlebox1, FALSE, FALSE, 0);

  toolbar2 = gtk_toolbar_new (GTK_ORIENTATION_HORIZONTAL, GTK_TOOLBAR_ICONS);
  gtk_widget_ref (toolbar2);
  gtk_object_set_data_full (GTK_OBJECT (compose), "toolbar2", toolbar2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toolbar2);
  gtk_container_add (GTK_CONTAINER (handlebox1), toolbar2);

  tmp_toolbar_icon = gnome_stock_pixmap_widget (compose, GNOME_STOCK_PIXMAP_MAIL_SND);
  button6 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar2),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Send"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (button6);
  gtk_object_set_data_full (GTK_OBJECT (compose), "button6", button6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button6);

  tmp_toolbar_icon = gnome_stock_pixmap_widget (compose, GNOME_STOCK_PIXMAP_SPELLCHECK);
  button7 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar2),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("button7"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (button7);
  gtk_object_set_data_full (GTK_OBJECT (compose), "button7", button7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button7);

  button8 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar2),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("button8"),
                                NULL, NULL,
                                NULL, NULL, NULL);
  gtk_widget_ref (button8);
  gtk_object_set_data_full (GTK_OBJECT (compose), "button8", button8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button8);

  table2 = gtk_table_new (4, 2, FALSE);
  gtk_widget_ref (table2);
  gtk_object_set_data_full (GTK_OBJECT (compose), "table2", table2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table2);
  gtk_box_pack_start (GTK_BOX (vbox2), table2, FALSE, FALSE, 0);

  optionmenu1 = gtk_option_menu_new ();
  gtk_widget_ref (optionmenu1);
  gtk_object_set_data_full (GTK_OBJECT (compose), "optionmenu1", optionmenu1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (optionmenu1);
  gtk_table_attach (GTK_TABLE (table2), optionmenu1, 0, 1, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  optionmenu1_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("To"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (optionmenu1_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("CC"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (optionmenu1_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("BCC"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (optionmenu1_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (optionmenu1), optionmenu1_menu);

  label9 = gtk_label_new (_("From\t"));
  gtk_widget_ref (label9);
  gtk_object_set_data_full (GTK_OBJECT (compose), "label9", label9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label9);
  gtk_table_attach (GTK_TABLE (table2), label9, 0, 1, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label10 = gtk_label_new (_("Subject"));
  gtk_widget_ref (label10);
  gtk_object_set_data_full (GTK_OBJECT (compose), "label10", label10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label10);
  gtk_table_attach (GTK_TABLE (table2), label10, 0, 1, 2, 3,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label11 = gtk_label_new (_("Date"));
  gtk_widget_ref (label11);
  gtk_object_set_data_full (GTK_OBJECT (compose), "label11", label11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label11);
  gtk_table_attach (GTK_TABLE (table2), label11, 0, 1, 3, 4,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  entry6 = gtk_entry_new ();
  gtk_widget_ref (entry6);
  gtk_object_set_data_full (GTK_OBJECT (compose), "entry6", entry6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry6);
  gtk_table_attach (GTK_TABLE (table2), entry6, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label12 = gtk_label_new ("");
  gtk_widget_ref (label12);
  gtk_object_set_data_full (GTK_OBJECT (compose), "label12", label12,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label12);
  gtk_table_attach (GTK_TABLE (table2), label12, 1, 2, 3, 4,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox2);
  gtk_object_set_data_full (GTK_OBJECT (compose), "hbox2", hbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox2);
  gtk_table_attach (GTK_TABLE (table2), hbox2, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  combo1 = gtk_combo_new ();
  gtk_widget_ref (combo1);
  gtk_object_set_data_full (GTK_OBJECT (compose), "combo1", combo1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo1);
  gtk_box_pack_start (GTK_BOX (hbox2), combo1, TRUE, TRUE, 0);

  combo_entry1 = GTK_COMBO (combo1)->entry;
  gtk_widget_ref (combo_entry1);
  gtk_object_set_data_full (GTK_OBJECT (compose), "combo_entry1", combo_entry1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_entry1);

  button5 = gtk_button_new_with_label (_("Identity List\t"));
  gtk_widget_ref (button5);
  gtk_object_set_data_full (GTK_OBJECT (compose), "button5", button5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button5);
  gtk_box_pack_start (GTK_BOX (hbox2), button5, FALSE, FALSE, 0);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox1);
  gtk_object_set_data_full (GTK_OBJECT (compose), "hbox1", hbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox1);
  gtk_table_attach (GTK_TABLE (table2), hbox1, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND),
                    (GtkAttachOptions) (GTK_EXPAND), 0, 0);

  entry5 = gtk_entry_new ();
  gtk_widget_ref (entry5);
  gtk_object_set_data_full (GTK_OBJECT (compose), "entry5", entry5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry5);
  gtk_box_pack_start (GTK_BOX (hbox1), entry5, TRUE, TRUE, 0);

  button3 = gtk_button_new_with_label (_("Recipient List"));
  gtk_widget_ref (button3);
  gtk_object_set_data_full (GTK_OBJECT (compose), "button3", button3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button3);
  gtk_box_pack_start (GTK_BOX (hbox1), button3, FALSE, FALSE, 0);

  button4 = gtk_button_new_with_label (_("Address Book"));
  gtk_widget_ref (button4);
  gtk_object_set_data_full (GTK_OBJECT (compose), "button4", button4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button4);
  gtk_box_pack_start (GTK_BOX (hbox1), button4, FALSE, FALSE, 0);

  scrolledwindow6 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow6);
  gtk_object_set_data_full (GTK_OBJECT (compose), "scrolledwindow6", scrolledwindow6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow6);
  gtk_box_pack_start (GTK_BOX (vbox2), scrolledwindow6, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow6), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  text2 = gtk_text_new (NULL, NULL);
  gtk_widget_ref (text2);
  gtk_object_set_data_full (GTK_OBJECT (compose), "text2", text2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (text2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow6), text2);

  statusbar1 = gtk_statusbar_new ();
  gtk_widget_ref (statusbar1);
  gtk_object_set_data_full (GTK_OBJECT (compose), "statusbar1", statusbar1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (statusbar1);
  gtk_box_pack_start (GTK_BOX (vbox2), statusbar1, FALSE, FALSE, 0);

  return compose;
}

GtkWidget*
create_delete_mbox (void)
{
  GtkWidget *delete_mbox;
  GtkWidget *dialog_vbox1;
  GtkWidget *label13;
  GtkWidget *dialog_action_area1;
  GtkWidget *button9;
  GtkWidget *button11;

  delete_mbox = gnome_dialog_new (_("Delete Mailbox"), NULL);
  gtk_object_set_data (GTK_OBJECT (delete_mbox), "delete_mbox", delete_mbox);
  gtk_window_set_policy (GTK_WINDOW (delete_mbox), FALSE, FALSE, FALSE);
  gnome_dialog_set_close (GNOME_DIALOG (delete_mbox), TRUE);

  dialog_vbox1 = GNOME_DIALOG (delete_mbox)->vbox;
  gtk_object_set_data (GTK_OBJECT (delete_mbox), "dialog_vbox1", dialog_vbox1);
  gtk_widget_show (dialog_vbox1);

  label13 = gtk_label_new (_("Are you sure you want to\ndelete this mailbox and\nall the messages in it?"));
  gtk_widget_ref (label13);
  gtk_object_set_data_full (GTK_OBJECT (delete_mbox), "label13", label13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), label13, FALSE, FALSE, 0);

  dialog_action_area1 = GNOME_DIALOG (delete_mbox)->action_area;
  gtk_object_set_data (GTK_OBJECT (delete_mbox), "dialog_action_area1", dialog_action_area1);
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (dialog_action_area1), 8);

  gnome_dialog_append_button (GNOME_DIALOG (delete_mbox), GNOME_STOCK_BUTTON_OK);
  button9 = GTK_WIDGET (g_list_last (GNOME_DIALOG (delete_mbox)->buttons)->data);
  gtk_widget_ref (button9);
  gtk_object_set_data_full (GTK_OBJECT (delete_mbox), "button9", button9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button9);
  GTK_WIDGET_SET_FLAGS (button9, GTK_CAN_DEFAULT);

  gnome_dialog_append_button (GNOME_DIALOG (delete_mbox), GNOME_STOCK_BUTTON_CANCEL);
  button11 = GTK_WIDGET (g_list_last (GNOME_DIALOG (delete_mbox)->buttons)->data);
  gtk_widget_ref (button11);
  gtk_object_set_data_full (GTK_OBJECT (delete_mbox), "button11", button11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button11);
  GTK_WIDGET_SET_FLAGS (button11, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (button9), "clicked",
                      GTK_SIGNAL_FUNC (on_mailboxdeleteok_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button11), "clicked",
                      GTK_SIGNAL_FUNC (on_mailboxdeletecancel_clicked),
                      NULL);

  return delete_mbox;
}

GtkWidget*
create_create_mbox (void)
{
  GtkWidget *create_mbox;
  GtkWidget *dialog_vbox2;
  GtkWidget *vbox3;
  GtkWidget *label14;
  GtkWidget *entry7;
  GtkWidget *dialog_action_area2;
  GtkWidget *button12;
  GtkWidget *button13;
  GtkWidget *button14;

  create_mbox = gnome_dialog_new (_("Create Mailbox"), NULL);
  gtk_object_set_data (GTK_OBJECT (create_mbox), "create_mbox", create_mbox);
  gtk_window_set_policy (GTK_WINDOW (create_mbox), FALSE, FALSE, FALSE);

  dialog_vbox2 = GNOME_DIALOG (create_mbox)->vbox;
  gtk_object_set_data (GTK_OBJECT (create_mbox), "dialog_vbox2", dialog_vbox2);
  gtk_widget_show (dialog_vbox2);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox3);
  gtk_object_set_data_full (GTK_OBJECT (create_mbox), "vbox3", vbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox3);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), vbox3, TRUE, TRUE, 0);

  label14 = gtk_label_new (_("Please enter the name of the mailbox\nyou want to create\n"));
  gtk_widget_ref (label14);
  gtk_object_set_data_full (GTK_OBJECT (create_mbox), "label14", label14,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (vbox3), label14, FALSE, FALSE, 0);

  entry7 = gtk_entry_new ();
  gtk_widget_ref (entry7);
  gtk_object_set_data_full (GTK_OBJECT (create_mbox), "entry7", entry7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry7);
  gtk_box_pack_start (GTK_BOX (vbox3), entry7, FALSE, FALSE, 0);

  dialog_action_area2 = GNOME_DIALOG (create_mbox)->action_area;
  gtk_object_set_data (GTK_OBJECT (create_mbox), "dialog_action_area2", dialog_action_area2);
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_END);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (dialog_action_area2), 8);

  gnome_dialog_append_button (GNOME_DIALOG (create_mbox), GNOME_STOCK_BUTTON_OK);
  button12 = GTK_WIDGET (g_list_last (GNOME_DIALOG (create_mbox)->buttons)->data);
  gtk_widget_ref (button12);
  gtk_object_set_data_full (GTK_OBJECT (create_mbox), "button12", button12,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button12);
  GTK_WIDGET_SET_FLAGS (button12, GTK_CAN_DEFAULT);

  gnome_dialog_append_button (GNOME_DIALOG (create_mbox), GNOME_STOCK_BUTTON_APPLY);
  button13 = GTK_WIDGET (g_list_last (GNOME_DIALOG (create_mbox)->buttons)->data);
  gtk_widget_ref (button13);
  gtk_object_set_data_full (GTK_OBJECT (create_mbox), "button13", button13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button13);
  GTK_WIDGET_SET_FLAGS (button13, GTK_CAN_DEFAULT);

  gnome_dialog_append_button (GNOME_DIALOG (create_mbox), GNOME_STOCK_BUTTON_CANCEL);
  button14 = GTK_WIDGET (g_list_last (GNOME_DIALOG (create_mbox)->buttons)->data);
  gtk_widget_ref (button14);
  gtk_object_set_data_full (GTK_OBJECT (create_mbox), "button14", button14,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button14);
  GTK_WIDGET_SET_FLAGS (button14, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (button12), "clicked",
                      GTK_SIGNAL_FUNC (on_mailboxcreateok_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button13), "clicked",
                      GTK_SIGNAL_FUNC (on_mailboxcreateapply_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button14), "clicked",
                      GTK_SIGNAL_FUNC (on_mailboxcreatecancel_clicked),
                      NULL);

  return create_mbox;
}

GtkWidget*
create_Rules (void)
{
  GtkWidget *Rules;
  GtkWidget *dialog_vbox3;
  GtkWidget *hpaned2;
  GtkWidget *hbox3;
  GtkWidget *scrolledwindow7;
  GtkWidget *clist1;
  GtkWidget *label15;
  GtkWidget *toolbar3;
  GtkWidget *tmp_toolbar_icon;
  GtkWidget *button21;
  GtkWidget *button22;
  GtkWidget *table3;
  GtkWidget *label16;
  GtkWidget *label17;
  GtkWidget *label18;
  GtkWidget *entry8;
  GtkWidget *combo2;
  GtkWidget *combo_entry2;
  GtkWidget *hbox4;
  GtkWidget *entry9;
  GtkWidget *optionmenu2;
  GtkWidget *optionmenu2_menu;
  GtkWidget *glade_menuitem;
  GtkWidget *rule_new_rule;
  GtkWidget *spaceholder;
  GtkWidget *dialog_action_area3;
  GtkWidget *button15;
  GtkWidget *button16;
  GtkWidget *button17;

  Rules = gnome_dialog_new (_("Rules"), NULL);
  gtk_object_set_data (GTK_OBJECT (Rules), "Rules", Rules);
  gtk_widget_set_usize (Rules, -2, 300);
  gtk_window_set_policy (GTK_WINDOW (Rules), TRUE, TRUE, TRUE);

  dialog_vbox3 = GNOME_DIALOG (Rules)->vbox;
  gtk_object_set_data (GTK_OBJECT (Rules), "dialog_vbox3", dialog_vbox3);
  gtk_widget_show (dialog_vbox3);

  hpaned2 = gtk_hpaned_new ();
  gtk_widget_ref (hpaned2);
  gtk_object_set_data_full (GTK_OBJECT (Rules), "hpaned2", hpaned2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hpaned2);
  gtk_box_pack_start (GTK_BOX (dialog_vbox3), hpaned2, TRUE, TRUE, 0);
  gtk_paned_set_position (GTK_PANED (hpaned2), 0);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox3);
  gtk_object_set_data_full (GTK_OBJECT (Rules), "hbox3", hbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox3);
  gtk_paned_pack1 (GTK_PANED (hpaned2), hbox3, FALSE, TRUE);

  scrolledwindow7 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow7);
  gtk_object_set_data_full (GTK_OBJECT (Rules), "scrolledwindow7", scrolledwindow7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow7);
  gtk_box_pack_start (GTK_BOX (hbox3), scrolledwindow7, TRUE, TRUE, 0);
  gtk_widget_set_usize (scrolledwindow7, 120, 68);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow7), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  clist1 = gtk_clist_new (1);
  gtk_widget_ref (clist1);
  gtk_object_set_data_full (GTK_OBJECT (Rules), "clist1", clist1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (clist1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow7), clist1);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 0, 80);
  gtk_clist_column_titles_hide (GTK_CLIST (clist1));

  label15 = gtk_label_new ("");
  gtk_widget_ref (label15);
  gtk_object_set_data_full (GTK_OBJECT (Rules), "label15", label15,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label15);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 0, label15);
  gtk_label_set_justify (GTK_LABEL (label15), GTK_JUSTIFY_LEFT);
  gtk_label_set_line_wrap (GTK_LABEL (label15), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label15), 0, 0);

  toolbar3 = gtk_toolbar_new (GTK_ORIENTATION_VERTICAL, GTK_TOOLBAR_ICONS);
  gtk_widget_ref (toolbar3);
  gtk_object_set_data_full (GTK_OBJECT (Rules), "toolbar3", toolbar3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toolbar3);
  gtk_box_pack_start (GTK_BOX (hbox3), toolbar3, FALSE, FALSE, 0);
  gtk_toolbar_set_button_relief (GTK_TOOLBAR (toolbar3), GTK_RELIEF_NONE);

  tmp_toolbar_icon = gnome_stock_pixmap_widget (Rules, GNOME_STOCK_PIXMAP_UP);
  button21 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar3),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Up"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (button21);
  gtk_object_set_data_full (GTK_OBJECT (Rules), "button21", button21,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button21);

  gtk_toolbar_append_space (GTK_TOOLBAR (toolbar3));

  tmp_toolbar_icon = gnome_stock_pixmap_widget (Rules, GNOME_STOCK_PIXMAP_DOWN);
  button22 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar3),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Down"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (button22);
  gtk_object_set_data_full (GTK_OBJECT (Rules), "button22", button22,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button22);

  table3 = gtk_table_new (4, 2, FALSE);
  gtk_widget_ref (table3);
  gtk_object_set_data_full (GTK_OBJECT (Rules), "table3", table3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table3);
  gtk_paned_pack2 (GTK_PANED (hpaned2), table3, TRUE, TRUE);
  gtk_table_set_row_spacings (GTK_TABLE (table3), 20);

  label16 = gtk_label_new (_("Rule name "));
  gtk_widget_ref (label16);
  gtk_object_set_data_full (GTK_OBJECT (Rules), "label16", label16,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label16);
  gtk_table_attach (GTK_TABLE (table3), label16, 0, 1, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label17 = gtk_label_new (_("regex"));
  gtk_widget_ref (label17);
  gtk_object_set_data_full (GTK_OBJECT (Rules), "label17", label17,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label17);
  gtk_table_attach (GTK_TABLE (table3), label17, 0, 1, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label18 = gtk_label_new (_("mbox"));
  gtk_widget_ref (label18);
  gtk_object_set_data_full (GTK_OBJECT (Rules), "label18", label18,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label18);
  gtk_table_attach (GTK_TABLE (table3), label18, 0, 1, 2, 3,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  entry8 = gtk_entry_new ();
  gtk_widget_ref (entry8);
  gtk_object_set_data_full (GTK_OBJECT (Rules), "entry8", entry8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry8);
  gtk_table_attach (GTK_TABLE (table3), entry8, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  combo2 = gtk_combo_new ();
  gtk_widget_ref (combo2);
  gtk_object_set_data_full (GTK_OBJECT (Rules), "combo2", combo2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo2);
  gtk_table_attach (GTK_TABLE (table3), combo2, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  combo_entry2 = GTK_COMBO (combo2)->entry;
  gtk_widget_ref (combo_entry2);
  gtk_object_set_data_full (GTK_OBJECT (Rules), "combo_entry2", combo_entry2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_entry2);

  hbox4 = gtk_hbox_new (FALSE, 4);
  gtk_widget_ref (hbox4);
  gtk_object_set_data_full (GTK_OBJECT (Rules), "hbox4", hbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox4);
  gtk_table_attach (GTK_TABLE (table3), hbox4, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  entry9 = gtk_entry_new ();
  gtk_widget_ref (entry9);
  gtk_object_set_data_full (GTK_OBJECT (Rules), "entry9", entry9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry9);
  gtk_box_pack_start (GTK_BOX (hbox4), entry9, TRUE, TRUE, 0);

  optionmenu2 = gtk_option_menu_new ();
  gtk_widget_ref (optionmenu2);
  gtk_object_set_data_full (GTK_OBJECT (Rules), "optionmenu2", optionmenu2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (optionmenu2);
  gtk_box_pack_start (GTK_BOX (hbox4), optionmenu2, FALSE, FALSE, 0);
  optionmenu2_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("Message"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (optionmenu2_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Header"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (optionmenu2_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Subject"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (optionmenu2_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("From"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (optionmenu2_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Recipients"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (optionmenu2_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Sender\t"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (optionmenu2_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Body"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (optionmenu2_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (optionmenu2), optionmenu2_menu);

  rule_new_rule = gtk_button_new_with_label (_("New Rule"));
  gtk_widget_ref (rule_new_rule);
  gtk_object_set_data_full (GTK_OBJECT (Rules), "rule_new_rule", rule_new_rule,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (rule_new_rule);
  gtk_table_attach (GTK_TABLE (table3), rule_new_rule, 1, 2, 3, 4,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (rule_new_rule), 25);

  spaceholder = gtk_label_new ("");
  gtk_widget_ref (spaceholder);
  gtk_object_set_data_full (GTK_OBJECT (Rules), "spaceholder", spaceholder,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (spaceholder);
  gtk_table_attach (GTK_TABLE (table3), spaceholder, 0, 1, 3, 4,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  dialog_action_area3 = GNOME_DIALOG (Rules)->action_area;
  gtk_object_set_data (GTK_OBJECT (Rules), "dialog_action_area3", dialog_action_area3);
  gtk_widget_show (dialog_action_area3);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area3), GTK_BUTTONBOX_END);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (dialog_action_area3), 8);

  gnome_dialog_append_button (GNOME_DIALOG (Rules), GNOME_STOCK_BUTTON_OK);
  button15 = GTK_WIDGET (g_list_last (GNOME_DIALOG (Rules)->buttons)->data);
  gtk_widget_ref (button15);
  gtk_object_set_data_full (GTK_OBJECT (Rules), "button15", button15,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button15);
  GTK_WIDGET_SET_FLAGS (button15, GTK_CAN_DEFAULT);

  gnome_dialog_append_button (GNOME_DIALOG (Rules), GNOME_STOCK_BUTTON_APPLY);
  button16 = GTK_WIDGET (g_list_last (GNOME_DIALOG (Rules)->buttons)->data);
  gtk_widget_ref (button16);
  gtk_object_set_data_full (GTK_OBJECT (Rules), "button16", button16,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button16);
  GTK_WIDGET_SET_FLAGS (button16, GTK_CAN_DEFAULT);

  gnome_dialog_append_button (GNOME_DIALOG (Rules), GNOME_STOCK_BUTTON_CANCEL);
  button17 = GTK_WIDGET (g_list_last (GNOME_DIALOG (Rules)->buttons)->data);
  gtk_widget_ref (button17);
  gtk_object_set_data_full (GTK_OBJECT (Rules), "button17", button17,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button17);
  GTK_WIDGET_SET_FLAGS (button17, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (clist1), "select_row",
                      GTK_SIGNAL_FUNC (on_rule_list_select_row),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button21), "clicked",
                      GTK_SIGNAL_FUNC (on_rule_up_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button22), "clicked",
                      GTK_SIGNAL_FUNC (on_rule_down_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (entry8), "changed",
                      GTK_SIGNAL_FUNC (on_rule_name_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (combo_entry2), "changed",
                      GTK_SIGNAL_FUNC (on_rule_mbox_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (entry9), "changed",
                      GTK_SIGNAL_FUNC (on_rule_regex_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (rule_new_rule), "clicked",
                      GTK_SIGNAL_FUNC (on_rule_new_rule_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button15), "clicked",
                      GTK_SIGNAL_FUNC (on_rule_ok_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button16), "clicked",
                      GTK_SIGNAL_FUNC (on_rule_apply_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button17), "clicked",
                      GTK_SIGNAL_FUNC (on_rule_cancel_clicked),
                      NULL);

  return Rules;
}

GtkWidget*
create_custom_mbox (void)
{
  GtkWidget *custom_mbox;
  GtkWidget *dialog_vbox4;
  GtkWidget *table4;
  GtkWidget *label19;
  GtkWidget *label20;
  GtkWidget *mbox_create_custom_name;
  GtkWidget *mbox_create_custom_query;
  GtkWidget *dialog_action_area4;
  GtkWidget *button23;
  GtkWidget *button24;
  GtkWidget *button25;

  custom_mbox = gnome_dialog_new (NULL, NULL);
  gtk_object_set_data (GTK_OBJECT (custom_mbox), "custom_mbox", custom_mbox);
  gtk_window_set_policy (GTK_WINDOW (custom_mbox), FALSE, FALSE, FALSE);

  dialog_vbox4 = GNOME_DIALOG (custom_mbox)->vbox;
  gtk_object_set_data (GTK_OBJECT (custom_mbox), "dialog_vbox4", dialog_vbox4);
  gtk_widget_show (dialog_vbox4);

  table4 = gtk_table_new (2, 2, FALSE);
  gtk_widget_ref (table4);
  gtk_object_set_data_full (GTK_OBJECT (custom_mbox), "table4", table4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table4);
  gtk_box_pack_start (GTK_BOX (dialog_vbox4), table4, TRUE, TRUE, 0);

  label19 = gtk_label_new (_("Name"));
  gtk_widget_ref (label19);
  gtk_object_set_data_full (GTK_OBJECT (custom_mbox), "label19", label19,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label19);
  gtk_table_attach (GTK_TABLE (table4), label19, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label19), 0, 0.5);

  label20 = gtk_label_new (_("Query"));
  gtk_widget_ref (label20);
  gtk_object_set_data_full (GTK_OBJECT (custom_mbox), "label20", label20,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label20);
  gtk_table_attach (GTK_TABLE (table4), label20, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label20), 0, 0.5);

  mbox_create_custom_name = gtk_entry_new ();
  gtk_widget_ref (mbox_create_custom_name);
  gtk_object_set_data_full (GTK_OBJECT (custom_mbox), "mbox_create_custom_name", mbox_create_custom_name,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (mbox_create_custom_name);
  gtk_table_attach (GTK_TABLE (table4), mbox_create_custom_name, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  mbox_create_custom_query = gtk_entry_new ();
  gtk_widget_ref (mbox_create_custom_query);
  gtk_object_set_data_full (GTK_OBJECT (custom_mbox), "mbox_create_custom_query", mbox_create_custom_query,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (mbox_create_custom_query);
  gtk_table_attach (GTK_TABLE (table4), mbox_create_custom_query, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  dialog_action_area4 = GNOME_DIALOG (custom_mbox)->action_area;
  gtk_object_set_data (GTK_OBJECT (custom_mbox), "dialog_action_area4", dialog_action_area4);
  gtk_widget_show (dialog_action_area4);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area4), GTK_BUTTONBOX_END);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (dialog_action_area4), 8);

  gnome_dialog_append_button (GNOME_DIALOG (custom_mbox), GNOME_STOCK_BUTTON_OK);
  button23 = GTK_WIDGET (g_list_last (GNOME_DIALOG (custom_mbox)->buttons)->data);
  gtk_widget_ref (button23);
  gtk_object_set_data_full (GTK_OBJECT (custom_mbox), "button23", button23,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button23);
  GTK_WIDGET_SET_FLAGS (button23, GTK_CAN_DEFAULT);

  gnome_dialog_append_button (GNOME_DIALOG (custom_mbox), GNOME_STOCK_BUTTON_APPLY);
  button24 = GTK_WIDGET (g_list_last (GNOME_DIALOG (custom_mbox)->buttons)->data);
  gtk_widget_ref (button24);
  gtk_object_set_data_full (GTK_OBJECT (custom_mbox), "button24", button24,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button24);
  GTK_WIDGET_SET_FLAGS (button24, GTK_CAN_DEFAULT);

  gnome_dialog_append_button (GNOME_DIALOG (custom_mbox), GNOME_STOCK_BUTTON_CANCEL);
  button25 = GTK_WIDGET (g_list_last (GNOME_DIALOG (custom_mbox)->buttons)->data);
  gtk_widget_ref (button25);
  gtk_object_set_data_full (GTK_OBJECT (custom_mbox), "button25", button25,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button25);
  GTK_WIDGET_SET_FLAGS (button25, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (button23), "clicked",
                      GTK_SIGNAL_FUNC (on_mboxcustomok_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button24), "clicked",
                      GTK_SIGNAL_FUNC (on_mboxcustomapply_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button25), "clicked",
                      GTK_SIGNAL_FUNC (on_mboxcustomcancel_clicked),
                      NULL);

  return custom_mbox;
}

