/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget *create_gems (void);
GtkWidget *create_about2 (void);
GtkWidget *create_menu1 (void);
GtkWidget *create_compose (void);
GtkWidget *create_delete_mbox (void);
GtkWidget *create_create_mbox (void);
GtkWidget *create_Rules (void);
