/*****************************************************************************
 *    GEMS Email Client                                                      *
 *                                                                           *
 *     Copyright (C) 2000-2009 Erik Greenwald <erik@smluc.org>               *
 *                                                                           *
 *     This program is free software; you can redistribute it and/or modify  *
 *     it under the terms of the GNU General Public License as published by  *
 *     the Free Software Foundation; either version 2 of the License, or     *
 *     (at your option) any later version.                                   *
 *                                                                           *
 *     This program is distributed in the hope that it will be useful,       *
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *     GNU General Public License for more details.                          *
 *                                                                           *
 *     You should have received a copy of the GNU General Public License     *
 *     along with this program; if not, write to the Free Software           *
 *     Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.             *
 *                                                                           *
 *****************************************************************************/

/*
 * $Id: interface.h,v 1.6 2009/08/31 13:45:29 erik Exp $
 */

/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget *create_gems (void);
GtkWidget *create_about2 (void);
GtkWidget *create_propertybox1 (void);
GtkWidget *create_readbox (void);
GtkWidget *create_vbox2 (void);
GtkWidget *create_scrolledwindow6 (void);
GtkWidget *create_dummywindow (void);
