/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget *create_gems (void);
GtkWidget *create_about2 (void);
GtkWidget *create_propertybox1 (void);
GtkWidget *create_readbox (void);
GtkWidget *create_vbox2 (void);
GtkWidget *create_scrolledwindow6 (void);
GtkWidget *create_dummywindow (void);
