/* Automatically generated by po2tbl.sed from gems.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"Failed to open spool\n", 2},
  {"Failed rewind\n", 3},
  {"\
%s: %s -> %s Subject: %s\n\
%s\n", 4},
  {"Couldn't flush list out of memory!\n", 5},
  {"Couldn't flush message out of memory!\n", 6},
  {"Couldn't close the spool\n", 7},
  {"Failed to initialize ruleset\n", 8},
  {"Failed to open spool %s\n", 9},
  {"\
\n\
Null body!\n", 10},
  {"Failed closing ruleset\n", 11},
};

int _msg_tbl_length = 11;
